name: Build Dev

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/*'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '*.md'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Change DNS Server
      shell: pwsh
      run: |
        $newDnsServers = @('1.1.1.1', '8.8.8.8')
        $networkAdapters = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' }
        foreach ($adapter in $networkAdapters) {
            Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ResetServerAddresses
            Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ServerAddresses $newDnsServers
        }
        ipconfig /flushdns

    - name: Generate version based on current date and time
      id: generate_version
      shell: pwsh
      run: |
        Set-TimeZone -Id "China Standard Time" -PassThru
        $date = Get-Date
        $year = $date.Year.ToString().Substring(2)
        $month = $date.Month.ToString("0")
        $day = $date.Day.ToString("0")
        $hour = $date.Hour.ToString("0")
        $minute = $date.Minute.ToString("0")
        $version = "$year.$month.$day.$hour$minute"
        echo "Version: $version"
        echo $PSVersionTable
        echo $GITHUB_OUTPUT
        echo "version=$version" >> $env:GITHUB_OUTPUT

    # - name: Install NSIS
    #   uses: repolevedavaj/install-nsis@v1.0.1
    #   with:
    #     nsis-version: 3.09

    - name: Build XROSC
      shell: cmd
      env:
        GITHUB_WORKFLOW_VERSION: ${{ steps.generate_version.outputs.version }}
      run: |
        cmd /c build.bat

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: XRSYS_OSC_CI_Build_v${{ steps.generate_version.outputs.version }}
        path: osc.exe